package org.example;

public enum Occupation {
    BILLEDKUNSTNER, BILLED_OG_LYDREDIGERING, CASTING, COLOURGRADING, DIRIGENTER,
    DRONE, DUKKESKABER, FORTÆLLER, FOTOGRAFER, FORLÆG,
    GRAFISKE_DESIGNERE, INDTALERE, KAPELMESTER, KLIPPER, PROGRAMKONCEPT,
    KONSULENT, KOR, KOREOGRAFI, LYDMESTER, TONEMESTER,
    LYDREDIGERING, LYS, MEDVIRKENDE, MUSIKERE, MUSIKALSK_ARRANGEMENT,
    ORKESTER_BAND, OVERSÆTTERE, PRODUCENT, PRODUCER, PRODUKTIONSKOORDINATOR,
    PROGRAMANSVARLIGE, TILRETTELÆGGELSE, REDAKTØREN, REKVISITØR, SCENOGRAFER,
    PRODUCERASSISTENT, SPECIAL_EFFECTS, SPONSORER, ANIMATION, TEKSTERE,
    TEKST_OG_MUSIK, TAK_TIL
}
